version: '3'

networks:
  traefik_net:
    external: true

services:
  code-server:
    image: codercom/code-server
    container_name: code-server
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
      - ${PWD}/.config:/home/coder/.config
      - ${PWD}/project:/home/coder/project
    user: ${UID}:${GID}  
    environment:
      - DOCKER_USER=$USER
    labels:
      traefik.enable: true
      traefik.http.routers.router-code.rule: Host(`code.mindlab.dev`)
      traefik.http.routers.router-code.entrypoints: websecure
      traefik.http.routers.router-code.middlewares: chain-no-auth-ws@file
      traefik.http.routers.router-code.tls: true
