version: '3'

networks:
  traefik_net:
    external: true

services:
  code-server:
    image: codercom/code-server
    container_name: code-server
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
 #     - ./.config:/home/coder/.config
 #     - ./project:/home/coder/project
 #     - ./.local:/home/coder/.local
      - ./coder:/home/coder
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 8080:8080
    labels:
#      traefik.enable: true
#      traefik.http.routers.router-code.rule: Host(`code.mindlab.dev`)
#      traefik.http.routers.router-code.entrypoints: websecure
#      traefik.http.routers.router-code.middlewares: chain-no-auth-ws@file
#      traefik.http.routers.router-code.tls: true
      com.centurylinklabs.watchtower.enable: true

